# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "static-1" do |conf|
    conf.vm.hostname = "static-1"
    conf.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "dynamic-1" do |conf|
    conf.vm.hostname = "dynamic-1"
    conf.vm.network "forwarded_port", guest: 8081, host: 8081
  end

end
