---
- name: Test if service exists
  stat: path="/etc/init.d/{{ cow_app_name }}"
  register: service_exists

- name: Stop service when exists
  service: name={{ cow_app_name }} state=stopped
  when: service_exists.stat.exists

- name: Install curl
  apt:  name=curl state=present

- name: Install Cowsay
  apt:  name=cowsay state=present

- name: Test if http-cowsay exists
  stat: path="{{ cow_app_script_path }}"
  register: httpcow_exists

- name: Download and unarchive http-cow
  unarchive: src="https://github.com/erikzaadi/http-cowsay/releases/download/v0.1/http-cow.tar.gz" dest="{{ cow_app_script_path | dirname }}" owner=root group=root mode=755 copy=no
  when: not httpcow_exists.stat.exists

- name: Generate service template
  template: src=cow-app-service.template dest="/etc/init.d/{{ cow_app_name }}" mode=755 owner=root group=root

- name: Start service
  service: name="{{ cow_app_name }}" state=started enabled=yes

- name: Health check
  uri: url="http://localhost:{{ cow_app_port }}" method=HEAD
