---
- name: Install Dependencies
  apt:  name=nginx state=present

- name: Install curl
  apt:  name=curl state=present

- name: Ensure that nginx is running
  service: name=nginx state=started

- name: Create static root dir
  file: path=/var/www/workshop state=directory owner=www-data group=www-data

- name: Copy static HTML files to root dir
  copy: src=index.html dest=/var/www/workshop owner=www-data group=www-data
  notify:
    - Reload nginx

- name: Disable default site in Nginx
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Generate our own nginx site
  copy: src=site.conf dest=/etc/nginx/sites-available/site.conf owner=www-data group=www-data
  notify:
    - Reload nginx

- name: Symlink our nginx site
  file: state=link src=/etc/nginx/sites-available/site.conf path=/etc/nginx/sites-enabled/site.conf owner=www-data group=www-data
  notify:
    - Reload nginx

- meta: flush_handlers

- name: Validate that nginx is installed
  uri:  url=http://127.0.0.1 method=HEAD
